### ISSUE TITLE
Port tests to Spek

### ISSUE THREAD

**Issue by sdeleuze** [mix-it/mixit#11]
[Spek](https://jetbrains.github.io/spek/) is a retty nice testing API running on top of JUnit 5 platform. Do you want to play with that @cbouttaz (I think you could like this kind of testing godness) by just porting the 2 JUnit tests we have, or do you want I take care of that ?

**Comment by cbouttaz** [comment]
The API is nice indeed but i couldn't manage to make it work 😢 

I followed the instructions from the [documentation](http://jetbrains.github.io/spek/docs/latest/#_gradle_kotlin_script) but when I build I get:

 `Caused by: org.gradle.api.UnknownDomainObjectException: Extension of type 'EnginesExtension' does not exist. Currently registered extension types: [DefaultExtraPropertiesExtension, SelectorsExtension_Decorated, FiltersExtension_Decorated]`

I tried to tweak a few things, including dependency versions and this [issue](https://github.com/JetBrains/spek/issues/139) but without success...

**Comment by sdeleuze** [comment]
Yeah the doc was not uptodate due to the fact we are using JUnit platform `1.0.0.M3`. It works now even I still would like to get rid of `@RunWith(JUnitPlatform::class)` (I asked the question on Kotlin Kotlin slack).
